---
name: Build

on: [push, pull_request]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get install libopenblas-dev liblapack-dev
      - run: make
      - run: make test
      - run: out/run_tests

  #  runs-on: windows-latest
  #  steps:
  #    - uses: actions/checkout@v2
  #    - run: choco install clapack
  #    - run: make
  #    - run: make test
  #    - run: test/run_tests

  mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: brew install openblas lapack
      - run: make
      - run: make test
      - run: out/run_tests
